services:
  backend:
    build: ./backend
    container_name: gold_flask
    env_file: .env
    volumes:
      - ./backend:/app
    ports:
      - "5003:5003"
    depends_on: []  # No longer depends on local db

  frontend:
    build: ./frontend
    container_name: gold_react
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    stdin_open: true
    tty: true

# Remove the volumes too (unless you use them elsewhere)
# volumes:
#   pgdata: